In [79]:
print("Hello World")

Hello World

In [80]:
print("time for machine learning")

time for machine learning

In [81]:
import numpy as np
import pandas as pd

In [82]:
df= pd.read_csv("bike_prices_dataset.csv")
df.head()

,S.no,Bike_company,Bike_model,Manufactured_year,Engine_warranty,Engine_type,Fuel_type,CC(Cubic capacity),Fuel_Capacity,Price
0,1,Bajaj,Avenger 220,2020,5.0,Single,Petrol,220CC,10 Litres,113000
1,2,TVS,Apache RTR,2020,5.0,V-twin,Petrol,120CC,11 Litres,70000
2,3,Hero,Passion,2020,5.0,Boxer,Petrol,140CC,12 Litres,85000
3,4,Honda,Activa 3G,2020,5.0,Single,Petrol,150CC,13 Litres,90000
4,5,Suzuki,Access,2020,5.0,V-twin,Petrol,350CC,14 Litres,65000

In [83]:
df.tail()

,S.no,Bike_company,Bike_model,Manufactured_year,Engine_warranty,Engine_type,Fuel_type,CC(Cubic capacity),Fuel_Capacity,Price
303,304,Bgauss,Bgauss B8,2017,3.0,Boxer,Petrol,185CC,19 Litres,81916
304,305,Bgauss,Bgauss Radiator,2017,3.0,Boxer,Petrol,205CC,20 Litres,82666
305,306,Bgauss,Bgauss Razor,2017,3.0,Boxer,Petrol,185CC,21 Litres,83416
306,307,Bgauss,Bgauss Flash,2017,3.0,Boxer,Petrol,205CC,22 Litres,84166
307,308,Bgauss,Bgauss Hash,2017,3.0,Boxer,Petrol,220CC,23 Litres,84916

In [84]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 308 entries, 0 to 307
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   S.no                308 non-null    int64
 1   Bike_company        308 non-null    object
 2   Bike_model          308 non-null    object
 3   Manufactured_year   308 non-null    int64
 4   Engine_warranty     306 non-null    float64
 5   Engine_type         308 non-null    object
 6   Fuel_type           308 non-null    object
 7   CC(Cubic capacity)  308 non-null    object
 8   Fuel_Capacity       307 non-null    object
 9   Price               308 non-null    int64
dtypes: float64(1), int64(3), object(6)
memory usage: 24.2+ KB

In [85]:
df.isna()
df =df.rename(columns={"CC(Cubic capacity)": "cubic_capacity",})

In [86]:
df.duplicated()
df['Fuel_Capacity'] = df['Fuel_Capacity'].str.replace("Litres","")
df[df['Fuel_Capacity'] == "Battery"]

,S.no,Bike_company,Bike_model,Manufactured_year,Engine_warranty,Engine_type,Fuel_type,cubic_capacity,Fuel_Capacity,Price
14,15,Lectro Electric,Gold,2020,2.0,Boxer,Electricity,120CC,Battery,65000
15,16,Li-ion Elektrik Solution,Silver,2020,2.0,Two-Stroke,Electricity,150CC,Battery,69000
16,17,Ather Energy,Energitic,2020,4.0,Two-Stroke,Electricity,130CC,Battery,73000
31,32,Lectro Electric,Leon,2014,2.0,Single,Electricity,120CC,Battery,62000
32,33,Li-ion Elektrik Solution,Ceon,2015,2.0,Single,Electricity,130CC,Battery,65000
33,34,Lectro Electric,Neon,1840,2.0,Single,Electricity,145CC,Battery,79000
73,74,Li-ion Elektrik Solution,Ceon,2016,2.0,Single,Electricity,130CC,Battery,65000
74,74,Li-ion Elektrik Solution,Prime,2017,3.0,Single,Electricity,125CC,Battery,61000
75,76,Li-ion Elektrik Solution,Power,2019,50.0,V-twin,Electricity,130CC,Battery,56700
76,77,Li-ion Elektrik Solution,Kurrent,2019,3.0,V-twin,Electricity,135CC,Battery,61000
77,78,Li-ion Elektrik Solution,Sunny,2017,3.0,V-twin,Electricity,140CC,Battery,65000
78,79,Li-ion Elektrik Solution,Leon,2017,3.0,V-twin,Electricity,150CC,Battery,65000
79,80,Li-ion Elektrik Solution,Deon,2020,5.0,Two-Stroke,Electricity,200CC,Battery,90000
80,81,Lectro Electric,Feon,2014,3.0,Single,Electricity,120CC,Battery,62000
82,83,Lectro Electric,Guide,2020,5.0,V-twin,Electricity,135CC,Battery,61000
83,84,Lectro Electric,Pride,2020,5.0,Two-Stroke,Electricity,10CC,Battery,66700
84,85,Lectro Electric,XSL,2020,5.0,Single,Electricity,150CC,Battery,71000
85,86,Lectro Electric,Peppy,2020,5.0,V-twin,Electricity,200CC,Battery,65000
86,87,Lectro Electric,Zeddy,2020,5.0,V-twin,Electricity,160CC,Battery,65000
125,126,Ather Energy,Energitic,2020,3.0,Two-Stroke,Electricity,135CC,Battery,74000
126,127,Ather Energy,Shiner,2019,3.0,V-twin,Electricity,134CC,Battery,64600
127,128,Ather Energy,Raina,2020,3.0,V-twin,Electricity,140CC,Battery,54800
128,129,Ather Energy,Grudge,2014,3.0,Two-Stroke,Electricity,155CC,Battery,74200
129,130,Ather Energy,Booster,2020,3.0,Two-Stroke,Electricity,167CC,Battery,63400
130,131,Ather Energy,XGB,2017,3.0,Two-Stroke,Electricity,176CC,Battery,73000
131,132,Ather Energy,YGB,2020,3.0,Two-Stroke,Electricity,190CC,Battery,92400
146,147,Lectro Electric,Bronze,2020,3.0,Boxer,Electricity,120CC,Battery,65000
147,148,Li-ion Elektrik Solution,Silver,2020,3.0,Two-Stroke,Electricity,150CC,Battery,69000
148,149,Ather Energy,Energitic,2020,3.0,Two-Stroke,Electricity,130CC,Battery,73000
212,213,Lectro Electric,Uno,2018,3.0,Single,Electricity,110CC,Battery,62500
213,214,Li-ion Elektrik Solution,Fiesta,2020,4.0,Single,Electricity,150CC,Battery,68000
214,215,Lectro Electric,Cyclone,1790,4.0,Single,Electricity,155CC,Battery,81000
215,216,Mahindra,Tsunami,2020,10.0,Single,Electricity,185CC,Battery,85000
217,218,Mahindra,Speedo,2018,6.0,Single,Electricity,155CC,Battery,79099
230,231,Odysse,Odysse Electric Evoqis,2020,5.0,Boxer,Electricity,125CC,Battery,50000
231,232,Odysse,Odysse Electric Evoqis XS,2020,5.0,Boxer,Electricity,150CC,Battery,55000
232,233,Odysse,Odysse Electric Evoqis XML,2020,5.0,Boxer,Electricity,175CC,Battery,69000
233,234,Odysse,Odysse Electric Evoqis HRT,2020,5.0,Boxer,Electricity,200CC,Battery,71000
234,235,Odysse,Odysse Electric Evoqis HP,2020,5.0,Boxer,Electricity,225CC,Battery,73000
235,236,Odysse,Odysse Electric Evoqis VIP,2020,5.0,Boxer,Electricity,250CC,Battery,75099

In [87]:
df['Fuel_Capacity'] = df['Fuel_Capacity'].str.extract(r'(\d+\.?\d*)').astype(dtype=float)

df[df['Fuel_type'] == "Electricity"]

,S.no,Bike_company,Bike_model,Manufactured_year,Engine_warranty,Engine_type,Fuel_type,cubic_capacity,Fuel_Capacity,Price
14,15,Lectro Electric,Gold,2020,2.0,Boxer,Electricity,120CC,NaN,65000
15,16,Li-ion Elektrik Solution,Silver,2020,2.0,Two-Stroke,Electricity,150CC,NaN,69000
16,17,Ather Energy,Energitic,2020,4.0,Two-Stroke,Electricity,130CC,NaN,73000
31,32,Lectro Electric,Leon,2014,2.0,Single,Electricity,120CC,NaN,62000
32,33,Li-ion Elektrik Solution,Ceon,2015,2.0,Single,Electricity,130CC,NaN,65000
33,34,Lectro Electric,Neon,1840,2.0,Single,Electricity,145CC,NaN,79000
34,35,Mahindra,Gutter,2020,5.0,Single,Electricity,135CC,16.0,65000
36,37,Mahindra,Shutter,2018,5.0,Single,Electricity,135CC,18.0,68000
73,74,Li-ion Elektrik Solution,Ceon,2016,2.0,Single,Electricity,130CC,NaN,65000
74,74,Li-ion Elektrik Solution,Prime,2017,3.0,Single,Electricity,125CC,NaN,61000
75,76,Li-ion Elektrik Solution,Power,2019,50.0,V-twin,Electricity,130CC,NaN,56700
76,77,Li-ion Elektrik Solution,Kurrent,2019,3.0,V-twin,Electricity,135CC,NaN,61000
77,78,Li-ion Elektrik Solution,Sunny,2017,3.0,V-twin,Electricity,140CC,NaN,65000
78,79,Li-ion Elektrik Solution,Leon,2017,3.0,V-twin,Electricity,150CC,NaN,65000
79,80,Li-ion Elektrik Solution,Deon,2020,5.0,Two-Stroke,Electricity,200CC,NaN,90000
80,81,Lectro Electric,Feon,2014,3.0,Single,Electricity,120CC,NaN,62000
81,82,Lectro Electric,Essentia,2020,5.0,V-twin,Electricity,130CC,NaN,250000
82,83,Lectro Electric,Guide,2020,5.0,V-twin,Electricity,135CC,NaN,61000
83,84,Lectro Electric,Pride,2020,5.0,Two-Stroke,Electricity,10CC,NaN,66700
84,85,Lectro Electric,XSL,2020,5.0,Single,Electricity,150CC,NaN,71000
85,86,Lectro Electric,Peppy,2020,5.0,V-twin,Electricity,200CC,NaN,65000
86,87,Lectro Electric,Zeddy,2020,5.0,V-twin,Electricity,160CC,NaN,65000
125,126,Ather Energy,Energitic,2020,3.0,Two-Stroke,Electricity,135CC,NaN,74000
126,127,Ather Energy,Shiner,2019,3.0,V-twin,Electricity,134CC,NaN,64600
127,128,Ather Energy,Raina,2020,3.0,V-twin,Electricity,140CC,NaN,54800
128,129,Ather Energy,Grudge,2014,3.0,Two-Stroke,Electricity,155CC,NaN,74200
129,130,Ather Energy,Booster,2020,3.0,Two-Stroke,Electricity,167CC,NaN,63400
130,131,Ather Energy,XGB,2017,3.0,Two-Stroke,Electricity,176CC,NaN,73000
131,132,Ather Energy,YGB,2020,3.0,Two-Stroke,Electricity,190CC,NaN,92400
146,147,Lectro Electric,Bronze,2020,3.0,Boxer,Electricity,120CC,NaN,65000
147,148,Li-ion Elektrik Solution,Silver,2020,3.0,Two-Stroke,Electricity,150CC,NaN,69000
148,149,Ather Energy,Energitic,2020,3.0,Two-Stroke,Electricity,130CC,NaN,73000
212,213,Lectro Electric,Uno,2018,3.0,Single,Electricity,110CC,NaN,62500
213,214,Li-ion Elektrik Solution,Fiesta,2020,4.0,Single,Electricity,150CC,NaN,68000
214,215,Lectro Electric,Cyclone,1790,4.0,Single,Electricity,155CC,NaN,81000
215,216,Mahindra,Tsunami,2020,10.0,Single,Electricity,185CC,NaN,85000
217,218,Mahindra,Speedo,2018,6.0,Single,Electricity,155CC,NaN,79099
230,231,Odysse,Odysse Electric Evoqis,2020,5.0,Boxer,Electricity,125CC,NaN,50000
231,232,Odysse,Odysse Electric Evoqis XS,2020,5.0,Boxer,Electricity,150CC,NaN,55000
232,233,Odysse,Odysse Electric Evoqis XML,2020,5.0,Boxer,Electricity,175CC,NaN,69000
233,234,Odysse,Odysse Electric Evoqis HRT,2020,5.0,Boxer,Electricity,200CC,NaN,71000
234,235,Odysse,Odysse Electric Evoqis HP,2020,5.0,Boxer,Electricity,225CC,NaN,73000
235,236,Odysse,Odysse Electric Evoqis VIP,2020,5.0,Boxer,Electricity,250CC,NaN,75099
277,278,22Kymco,Flow,2020,5.0,Boxer,Electricity,130CC,10.0,55000
278,279,22Kymco,iFlow,2020,5.0,Boxer,Electricity,145CC,11.0,54700
279,280,22Kymco,Fiesta,2020,4.0,Single,Electricity,160CC,12.0,59760
280,281,22Kymco,Benzo,2020,5.0,Single,Electricity,185CC,13.0,61568
281,282,22Kymco,Like EV,2020,5.0,Single,Electricity,205CC,14.0,63599
282,283,22Kymco,Like 200,2020,5.0,Single,Electricity,220CC,15.0,67989
283,284,22Kymco,X-Town,2020,5.0,Single,Electricity,235CC,16.0,69879

In [88]:
df.fillna({'Fuel_Capacity': 0}, inplace=True)
df['Is_Electric'] = df['Fuel_type'] == "Electricity"
df.head()

,S.no,Bike_company,Bike_model,Manufactured_year,Engine_warranty,Engine_type,Fuel_type,cubic_capacity,Fuel_Capacity,Price,Is_Electric
0,1,Bajaj,Avenger 220,2020,5.0,Single,Petrol,220CC,10.0,113000,False
1,2,TVS,Apache RTR,2020,5.0,V-twin,Petrol,120CC,11.0,70000,False
2,3,Hero,Passion,2020,5.0,Boxer,Petrol,140CC,12.0,85000,False
3,4,Honda,Activa 3G,2020,5.0,Single,Petrol,150CC,13.0,90000,False
4,5,Suzuki,Access,2020,5.0,V-twin,Petrol,350CC,14.0,65000,False

In [89]:
df['cubic_capacity'] = df['cubic_capacity'].str.replace("CC","").astype(dtype=int)
df['Bike_model'].nunique()

237

In [90]:
df_enocded = pd.get_dummies(df, drop_first= True, columns=["Engine_type", "Fuel_type", "Is_Electric","Bike_company"],dtype= int)
df_enocded.head()

,S.no,Bike_model,Manufactured_year,Engine_warranty,cubic_capacity,Fuel_Capacity,Price,Engine_type_Dual Stroke,Engine_type_Oxidiser-Air inlet,Engine_type_Single,...,Bike_company_Li-ion Elektrik Solution,Bike_company_Mahindra,Bike_company_Odysse,Bike_company_Okinawa,Bike_company_Revolt Motors,Bike_company_Royal Enfield,Bike_company_Suzuki,Bike_company_TVS,Bike_company_Triumph,Bike_company_Yamaha
0,1,Avenger 220,2020,5.0,220,10.0,113000,0,0,1,...,0,0,0,0,0,0,0,0,0,0
1,2,Apache RTR,2020,5.0,120,11.0,70000,0,0,0,...,0,0,0,0,0,0,0,1,0,0
2,3,Passion,2020,5.0,140,12.0,85000,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,4,Activa 3G,2020,5.0,150,13.0,90000,0,0,1,...,0,0,0,0,0,0,0,0,0,0
4,5,Access,2020,5.0,350,14.0,65000,0,0,0,...,0,0,0,0,0,0,1,0,0,0

In [91]:
from sklearn.model_selection import train_test_split

In [92]:
y = df_enocded["Price"].to_numpy()
X = df_enocded.drop(["Price", "S.no","Bike_model"],axis= 1).to_numpy()

print(y)

[ 113000   70000   85000   90000   65000  180000   65000  150000   89000
   99999  250000  350000  130000  340000   65000   69000   73000   89000
   99000   74000   79999   87999  185999   90000   99999   55000  350000
  459999  330000  449090  529999   62000   65000   79000   65000   70000
   68000   77990   89000  189000  240000  300000  358999  550000  590000
  623000  650000  890000  990000 1200000 1234500  679999  549999  767888
  898999  124500  145000  219500  232000  124500  135000   70000   64000
   79999   75000   89000  125000   75000   77000   81000   55000   56700
   61000   65000   61000   56700   61000   65000   65000   90000   62000
  250000   61000   66700   71000   65000   65000  260000  219500  232000
  124500  260000  219500  232000  450000  650000  790000  103000  101000
  650000  790000  103000  124500  134500   64500   65000   79000  103000
  101000  650000  790000  103000  124500  134500  790000  103000  124500
  134500  650000  790000  950000  990000  790000  950000  123400   74000
   64600   54800   74200   63400   73000   92400  114000   80000   86000
   91000   66000  189000   65000  130000   86000   99599  250000  350000
  130000  340000   65000   69000   73000   89000   99000   74000   79999
   97999  195999   99000  109000   64000   69999   87999  195999  189000
   64000  135000   87000   95599  255000  355000  135000  345000   99000
   74000   79999   87999  185999   90000   99999   55000  350000  459999
  180000   76000   81000  106000  289000   63000  150000   66000  199599
  350000  380000  230000  440000   96000   85000   76000  199000   67000
  135000   66000   95599  260099  550000  190099   95000  109999   73500
  320000  489999  310000  409090  629999   62500   68000   81000   85000
   73000   79099   84099   77999   97999  195999  190000  199999  155000
  390000  359999  320000  439090  629999   50000   55000   69000   71000
   73000   75099  155000  390000  359999  320000  439090  629999  449090
  459090  490000  389999  320900  539090  679999  678999  689999  579909
  579999  479999  379999  879999  978999 1089999 1179909 1579999 1379999
  399999  545909  989999  619999  809999  109999  123456 1679900 1779990
  150000  179999  155000  189000  145000  259999  249999   55000   54700
   59760   61568   63599   67989   69879   74500   75000   76500   77500
   74500   76550   76590   61568   63599   67989   69879   74500   75000
   76500   80000   78000   79666   80416   81166   81916   82666   83416
   84166   84916]

In [93]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.20, random_state=42)

print(y_train)
print(y_test)

[  64600  650000  539090   73000  550000   65000   69000  124500  650000
   65000   81000  529999  185999  545909  145000   73000   86000  489999
   55000  190099  130000  355000  124500  199999  125000  124500   79999
  689999   74000   65000   90000   76500   77500   61000   69000  250000
  189000  359999  103000   77000  439090   77990   73000  124500  195999
   54700   75000  103000   81000   62000  106000   64000  390000  123400
   99000 1179909  790000  130000  114000   65000 1379999   79999   74000
  399999   95000   81916   67989   90000   96000   84099   63599   63400
   89000  320900   55000  350000  124500   99999  134500   75000   59760
  389999   63000   71000   85000  103000   85000  150000  950000  190000
  123456   54800   61000  449090   66700  978999  103000   76590   95599
   80000   67989  439090   89000  310000   65000  390000   87999  130000
   70000  330000   99000  250000  379999   92400  180000  679999  650000
   77999  350000   69000  300000  232000  629999   66000  350000   80416
   99599  629999  113000   61568   61568  790000  440000  809999  134500
   74000  101000   68000   70000   99000  678999   68000  879999  350000
   82666   95599  259999  459999   55000   65000  790000   65000   97999
   64000  195999  109999   65000   64000   85000   91000   74200   80000
   89000   55000  155000   75000  590000  679999  109000  240000  950000
   69879   73000   97999   90000 1679900  790000  250000  155000  320000
   62500  189000  479999   78000 1779990   66000   65000  890000  450000
  179999  320000   63599  260099  189000  550000   79099  380000   65000
  767888   70000 1200000   62000  109999   65000  989999  260000  549999
  619999  629999  340000  219500  255000   81166   86000   74500  459090
  898999 1234500  185999  350000   84166   66000  345000  232000  990000
   75099  579999   87999  195999  249999  230000 1089999   89000   73000
   74000  650000  260000   81000  990000   84916   79999  199599   56700
   79000  150000  124500]
[  74500   99999  219500  135000   55000   79999  219500  289000  490000
  650000   56700  135000   69879   83416   74500   76550  180000   99000
   87000  135000   65000   64500  189000   73500   61000   87999  134500
   79000  145000  579909  101000   90000   61000 1579999  232000  103000
  623000   89000   67000  790000  358999   99999  459999  449090   75000
  199000  359999  150000   76500   65000  790000  320000  340000   71000
   76000   50000   79666  135000   76000  409090  155000   69999]

In [94]:

def standardize_data(X_train, X_test):
     """
    Standardizes the input data using mean and standard deviation.

    Parameters:
        X_train (numpy.ndarray): Training data.
        X_test (numpy.ndarray): Testing data.

    Returns:
        Tuple of standardized training and testing data.
    """
     
     mean = np.mean(X_train, axis= 0)
     std = np.std(X_train,axis=0)


     X_train = (X_train - mean)/std

     X_test = (X_test - mean)/std

     return X_train, X_test


X_train , X_test = standardize_data(X_train,X_test)
print(X_train)

[[ 0.07966621         nan -0.74865663 ... -0.17113943 -0.24565184
  -0.26375219]
 [ 0.03672605         nan  0.12486804 ... -0.17113943 -0.24565184
   3.79143772]
 [ 0.07966621         nan -0.4687895  ... -0.17113943 -0.24565184
  -0.26375219]
 ...
 [ 0.08825425         nan -0.25676895 ... -0.17113943 -0.24565184
   3.79143772]
 [ 0.08825425         nan -0.25676895 ... -0.17113943 -0.24565184
  -0.26375219]
 [ 0.08825425         nan -0.25676895 ... -0.17113943 -0.24565184
  -0.26375219]]